version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
        #  web:
        #     image:  frehiwot2112/sample-wagtail:v8
        #     volumes: 
        #       - .:/app
    ports:
        - "8000:8000"

# docker-compose up --build -d